### ISSUE TITLE
security_groups bootstrap option doesn't work with an existing group

### ISSUE THREAD

**Issue by msonnabaum** [chef/chef-provisioning-aws#174]
Using the `security_groups` parameter with an existing security group like so:

```ruby
with_machine_options bootstrap_options: {
  security_groups: "some-group-name",
}
```

Resulted in the following error:
```
Chef::Resource::AwsSecurityGroup[some-group-name] does not exist!
```

I changed it to use `security_group_ids` instead just to see if it would work, and it did.

**Comment by Joseph-R** [comment]
I replicated this last week.

Spoke briefly with @tyler-ball on another matter, and he suggested chef-izing the security group first, then passing the resource name of that SG into the machine resource.

```
require 'chef/provisioning/aws_driver'

with_driver 'aws::us-east-1'

aws_security_group "hortonworks_chef" do
  vpc  'vpc-45817320'
  inbound_rules [
    {:port => 22, :protocol => :tcp, :sources => ["0.0.0.0/0"] },
  ]
end

machine 'tester' do
  tag 'test_successful'
  recipe 'hdp::default'
  machine_options :bootstrap_options => {
    :key_name => 'korrelate2012',
    :image_id => 'ami-b23009da', 
    :subnet => 'subnet-aebab1da',
    :security_groups => [ 'hortonworks_chef' ],
    :instance_type => 'm3.medium',
  }, :ssh_username => 'ec2-user'
end
```

I tried that over the weekend and still run into the following error:
```
[2015-05-04T11:39:33-04:00] FATAL: Stacktrace dumped to /Users/jreid/repo/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 8.243118 seconds
[2015-05-04T11:39:33-04:00] ERROR: machine[tester] (@recipe_files::/Users/jreid/repo/chef-repo/cookbooks/hdp/recipes/simple.rb line 30) had an error: AWS::EC2::Errors::MissingParameter: When specifying a security group you must specify a group id for each item
[2015-05-04T11:39:33-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Stack trace posted [here](https://gist.github.com/Joseph-R/72c98e0497f7c78877e9).

**Comment by tyler-ball** [comment]
@msonnabaum and @Joseph-R - would you mind trying with https://github.com/chef/chef-provisioning-aws/pull/194 and seeing if you still encounter this issue?

**Comment by Joseph-R** [comment]
@tyler-ball - Sure thing.  How do I go about doing that?

I am currently on the following versions:
```
$ chef -v
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
[17:02:55] (2) jreid@JoesMacBookPro:~
$ gem list aws

*** LOCAL GEMS ***

aws-sdk-v1 (1.64.0)
chef-provisioning-aws (1.1.1, 1.0.4)
fog-aws (0.1.2)
```

I assume I need to pull a branched version of the chef-provisioning-aws gem?

**Comment by tyler-ball** [comment]
@Joseph-R The easiest way to do it is to write a Gemfile with the following contents at the root of your cookbook:

```ruby
gem 'chef-provisioning-aws', :git => 'https://github.com/chef/chef-provisioning-aws', :branch => 'tball/sgbyname'
```

The run `bundle install` and `bundle exec chef-client -z` from now on.  This will no longer use the `chef-client` executable from your ChefDK install, though.

The other choice is to download the source you want, run `gem build` on it and then `chef gem install` on the .gem file that is created.  That will install the gem into your ChefDK, but you will probably also have to use `chef gem uninstall chef-provisioning-aws` to uninstall the existing installed versions first.  I think the bundle approach is better because it doesn't mess with the ChefDK.

**Comment by Joseph-R** [comment]
@tyler-ball - Gotcha.  

Confirmed working with the following recipe:
```
require 'chef/provisioning/aws_driver'

with_driver 'aws::us-east-1'

aws_security_group "sg_name" do
  vpc  'vpc-45817320'
  inbound_rules [
    # Allow SSH from all.
    {:port => 22..22, :protocol => :tcp, :sources => ["0.0.0.0/0"] }
  ]
end

machine 'testy_3' do
  tag 'test_successful'
  action :ready
  machine_options :bootstrap_options => {
    :instance_type => 'm3.medium',
    :subnet => 'subnet-aebab1da',
    :security_groups => [ 'sg_name' ],
    :image_id => 'ami-04070c6c', 
    :key_name => 'korrelate2012'
  },
  :ssh_username => 'ec2-user',
  :use_private_ip_for_ssh => true
end
```

**Comment by tyler-ball** [comment]
This should be fixed in https://github.com/chef/chef-provisioning-aws/issues/194 - Security Groups no longer need data bags!  You can load an existing security group with `aws_security_group 'name'`.  If there are 2 security groups with the same name in a given VPC, you will also have to provide the `vpc` attribute.
