### ISSUE TITLE
 Invalid value 'Must specify both from and to ports with TCP/UDP.' for portRange.

### ISSUE THREAD

**Issue by ikozel** [chef/chef-provisioning-aws#183]
definition of security group error out:   
aws_security_group 'provisioning-test-sg1' do
   vpc 'vpc-99999ffc'
   inbound_rules [
         {:ports => 3300..3306, :protocol => :tcp, :sources => ["0.0.0.0/0"] },
         {:ports => 22..22, :protocol => :udp, :sources => ["0.0.0.0/0"] }
       ]
   outbound_rules [
         {:ports => 2220..2223, :protocol => :tcp, :destinations => ["0.0.0.0/0"] },
         {:ports => 8080..8090, :protocol => :tcp, :destinations => ["0.0.0.0/0"] }
       ]
end

===============================================================================
    Error executing action `create` on resource 'aws_security_group[provisioning-test-sg1] (sg-491e612d)'
 ===============================================================================
    AWS::EC2::Errors::InvalidParameterValue
    ---------------------------------------
    Invalid value 'Must specify both from and to ports with TCP/UDP.' for portRange.
    
Any idea what is missing?

**Comment by georgecook-cbt** [comment]
I was just battling with the same error but it turned out I had specified ":port", not ":ports" with an "s" since I was grabbing examples from https://github.com/chef/chef-provisioning-aws/blob/master/docs/examples/sg_test.rb 

Point being, you can get that error when there's a larger syntax issue with the declaration versus just the ports being funny.

**Comment by ikozel** [comment]
thanks @georgecook-cbt use of port instead of ports fixed the problem.
