### ISSUE TITLE
cannot build machine using from_image in AWS 

### ISSUE THREAD

**Issue by ikozel** [chef/chef-provisioning-aws#193]
machine will not build using from_image. The AMI qa_node_image_349_99992  is created by machine_image with the same AWS account successfully. 
-----------------------
```ruby
machine "qa_node_349_99992" do
  from_image "qa_node_image_349_99992"
  machine_options(
    :ssh_username => 'ubuntu',
    :bootstrap_options => {
      :instance_type => 'm1.small',
      :key_name => 'devops',
      :subnet_id => 'subnet-4444444'
    } 
  )
  converge true
  tag "qa_node_349_99992"
end
```
-----------------------
I can create machine using image_id for the same image just fine.
-----------------------
```ruby
machine "qa_node_349_99992" do
  machine_options(
    :ssh_username => 'ubuntu',
    :bootstrap_options => {
      :image_id => 'ami-0a44df1',
      :instance_type => 'm1.small',
      :key_name => 'devops',
      :subnet_id => 'subnet-4444444'
    } 
  )
  converge true
  tag "qa_node_349_99992"
end
```
---------------

**Comment by joelwilson** [comment]
Same problem here :+1:

**Comment by tyler-ball** [comment]
Another report from #211 - the following doesn't work:

```
machine_image "new_image" do
  chef_server( :chef_server_url => 'http://localhost:8889')  # workaround chef-zero problem
end

machine "new_machine" do
  from_image "new_image"
  chef_server( :chef_server_url => 'http://localhost:8889')  # workaround chef-zero problem
end
```

**Comment by tyler-ball** [comment]
It looks like we just never implemented the functionality to make `from_image` work :(

**Comment by Fodoj** [comment]
I can understand that there was no time to implement it, but why to put none-existing functionality into docs? https://github.com/chef/chef-provisioning-aws/blob/8e258dfcad9315318d31dcd8b6e316d16f7674a4/docs/examples/ref_full.rb#L143

**Comment by Fodoj** [comment]
I've came up with following hack (in case someone needs it):

```ruby
machine_image "app-node-ami" do
end

machine "app-node" do
  machine_options(
    lazy do
      image_id = search(:machine_image, "id:app-node-ami").first["reference"]["image_id"]
      Chef::Mixin::DeepMerge.merge(common_machine_options, { bootstrap_options: { image_id: image_id } })
    end
  )
end
```

Works fine, though looks a bit ugly (mostly because I need to reuse common_machine_options and merge them by hand.

Is there a better solution?

**Comment by tyler-ball** [comment]
@Fodoj Thank you for the temporary workaround!

**Comment by Fodoj** [comment]
@tyler-ball is this feature already being worked on? do you need any help with that?

**Comment by tyler-ball** [comment]
This bug is not being worked on.  If you want to take a stab at it, that would be awesome!

**Comment by tyler-ball** [comment]
UPDATE - https://github.com/chef/chef-provisioning/pull/366 (specifically https://github.com/chef/chef-provisioning/pull/366#issuecomment-123477922) was released in `chef-provisioning` 1.3.0.

It looks like `from_image` should be available in the `machine_options` parameter to [`allocate_machine`](https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L479) when using `chef-provisioning` 1.3.0.  Because of this, you should be able to add `new_resource.from_image` to the list of `||`ed options in https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L663.  The [lookup_options](https://github.com/chef/chef-provisioning-aws#lookup_options) method should then automatically convert the resource name to an ami id.

Would you mind opening a new PR for this and testing it?  This should also be covered by an integration test.

**Comment by Fodoj** [comment]
Sure, I'll try to open PR in next few days

**Comment by Fodoj** [comment]
Yay, look works as expected, tested it with simple recipe like this:

```ruby
machine_image "app-web-ami" do
end

machine "app-web" do
  from_image "app-web-ami"
end
```
