### ISSUE TITLE
Machine with name that could be instance id is not being destroyed

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#232]
I'm using chef-provisioning 1.2.0 and chef-provisioning 1.2.1. I run:

```
machine 'i-5b573cac' do
end
```

and then:

```
machine 'i-5b573cac' do
  action :destroy
end
```
The destroy recipe runs without error, and reports deleting the node and the client. But it does NOT destroy the actual instance on EC2.

However, if I do the above but use the logical name 'test', it works and destroys the instance. So I am guessing it is because the name could be an AWS instance ID.

**Comment by christinedraper** [comment]
Also occurs on current dev driver 1.3.0.dev.0

**Comment by tyler-ball** [comment]
This certainly seems like a straightforward bug that we could also write a test for when we fix it - thanks @christinedraper!

**Comment by djapg** [comment]
I'm seeing this as well (can't kill the instance, but everything else gets cleaned up) when I change the Amazon Name tag to something else instead of the logical name. I would love to have this functionality so we can have human readable names in the console that aren't necessarily the logical name or the node name (I set the Chef provisioning logical name as another tag named chef).

**Comment by tyler-ball** [comment]
Oh fun - this is failing because [current_driver](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provider/machine.rb#L106-L110) doesn't know of a `machine_spec` for `i-5b573cac`.  It only knows of a machine spec for `test`.

I'm thinking to fix this we could add a reverse lookup on the machine_spec for chef-provisioning-aws.  Basically, if it doesn't find a machine_spec named `i-5b573cac` then it iterates through all machine specs and looks for 1 with an id of `i-5b573cac`.

**Comment by tyler-ball** [comment]
@djapg Because we store the mapping from `'test'` (resource name) to `'i-5b573cac'` (instance ID) in a data bag right now, you should be able to safely change the Name tag on the instance without affecting Chef's ability to manage the node.

**Comment by tyler-ball** [comment]
I have a temporary workaround - you can use

```ruby
aws_instance 'i-5b573cac' do
  action :destroy
end
```

This will successfully delete the instance.  Unfortunately it will leave the `'test'` Chef Node object around.  Again, this is because we don't have a reverse mapping from `'i-5b573cac'` to `'test'`

**Comment by tyler-ball** [comment]
@djapg @christinedraper if my workaround will satisfy for now, I'll close this issue and open a new issue in chef-provisioning to cover the idea that we need to be able to lookup items in the Entry Store by values and not just keys

**Comment by christinedraper** [comment]
I'm not clear how lookup by value fixes the problem - won't there still need to be changes  in chef-provisioning-aws?

**Comment by tyler-ball** [comment]
@christinedraper What do you mean 'lookup by value'?  I'm proposing using the `aws_instance` resource instead of the `machine` resource to delete the object if you only know the id.  The `aws_instance` resource usage I proposed [above](https://github.com/chef/chef-provisioning-aws/issues/232#issuecomment-124594796) works right now.

**Comment by christinedraper** [comment]
I'm OK with the workaround - well, actually I will instead avoid using instance IDs as names for now.  

I'm just really unclear on how "the idea that we need to be able to lookup items in the Entry Store by values and not just keys" would address the underlying issue in the future. Perhaps something you can help me understand at office  hours!

**Comment by tyler-ball** [comment]
Closing this since we have a workaround.  @christinedraper see https://github.com/chef/chef-provisioning/issues/401 and maybe it will help clarify what I am talking about?  If not, we can talk about it tomorrow in office hours.
