### ISSUE TITLE
Enable ELB attributes to be retrieved from knife or a recipe

### ISSUE THREAD

**Issue by tpetchel** [chef/chef-provisioning-aws#27]
for example, the public DNS name

**Comment by jkeiser** [comment]
IMO we should go the other way, and make the resources two-way.  But either way, it needs to be easy to get this information.

**Comment by gmiranda23** [comment]
It's worth noting that the new aws_object method does not seem to apply to the load_balancer resource (because that's in core provisioning?).  Trying to retrieve settings via lazy attributes on ELBs produces a NoMethodError.

    NoMethodError
    -------------
    undefined method `aws_object' for Chef::Resource::LoadBalancer

**Comment by christinedraper** [comment]
@gmiranda23 How to get the aws_object from the base provisioning resources is documented here:

https://github.com/chef/chef-provisioning-aws#looking-up-chef-provisioning-resources

But I'd say +1 for a uniform way of getting at aws_object across all resources (and of associating them with existing real AWS resources).

**Comment by gmiranda23** [comment]
@christinedraper It seems boilerplate enough to consider a uniform approach to lookup options.  @jkeiser 's original direction was that it should be easy to get this information.  I agree that the data_bag approach is less preferable.  But regardless, it should be accessible in a consistent manner.

**Comment by christinedraper** [comment]
The discussion I had re this with @tyler-ball during office hours was about changing chef provisioning base resources so that providers can directly extend them. Then an aws_object method could be directly accessible on both base resources like machine, and AWS specific resources. This would be a significant change, though, so would need to be a major version change. 

I believe/hope the same change could also make it easier to associate a machine resource with an existing AWS instance, which is another thing I've been running into.

**Comment by alexmanly** [comment]
:+1:

**Comment by Karnifexx** [comment]
+1

**Comment by tyler-ball** [comment]
Do the instructions at https://github.com/chef/chef-provisioning-aws#looking-up-chef-provisioning-resources still work as a workaround until we can get something better?

**Comment by bigboxsoftware** [comment]
+1

**Comment by OwenTuz** [comment]
:+1:

**Comment by darnould** [comment]
:+1:

**Comment by allanchaplin** [comment]
+1

**Comment by miggy282** [comment]
:thumbsup:

**Comment by gmiranda23** [comment]
@tyler-ball Look up of instances works via the method in the README.  Lookup of ELBs results in the same issue seen in #242

**Comment by tyler-ball** [comment]
This will be fixed by adding the `aws_object` method the `machine`, `machine_batch` and `load_balancer` resources as part of https://github.com/chef/chef-provisioning-aws/pull/346 - see https://github.com/chef/chef-provisioning-aws/pull/346#issuecomment-144447869 for an example of what the recipes would look like.
