### ISSUE TITLE
Instances not being destroyed since version 1.2.0

### ISSUE THREAD

**Issue by kreisys** [chef/chef-provisioning-aws#379]
Hello,
I've been trying different versions of chef-provisioning-aws and it seems that this problem was introduced in version 1.2.0, or more specifically by commit 18f5172b2743f486186b169ca8d5e49d9d35f1e5 (merge of pr #192). Basically I'm running this very simple recipe (chef-client -z recipe.rb):

<pre>
with_driver 'aws::us-east-1'
with_chef_server 'https://my.chef.server.goes.here',
  client_name: Chef::Config[:node_name],
  signing_key_filename: Chef::Config[:client_key]

machine 'testaws' do
  machine_options({
    bootstrap_options: {
      image_id: 'ami-aa7ab6c2',
      instance_type: 't1.micro'
    }
  })
  action :converge
  #action :destroy
end
</pre>

This is supposed to run provisioning in local mode, but the provisioned instance should converge using my full-fledged chef server. Running this creates and converges the instance just fine, however, when commenting the :converge line and uncommenting the :destroy line and running again, the client and node objects are removed from the chef server, but the instance is still on EC2. Doing the exact same thing with the previous commit (23bffc7da7e28fbf5e9ba3f5826adc4d1071466e) works as expected and the instance is destroyed. Also to add to the confusion, when not pointing to a Chef server (thus letting it use the local chef-zero instance), the instance is being destroyed just fine. Can anyone try to confirm this? It could be something I'm doing wrong... it's strange that a bug like this would go unnoticed for 4 minor versions (I also reproduced it with current master...). I've done as much as I can to pinpoint this... Please help :)

**Comment by kreisys** [comment]
So after diving into the code and trying some things it seems that the culprit is here:
https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L627-L639

```ruby
        aws_instance machine_spec.name do
          action :destroy
          driver d
        end
```
I'm not 100% sure how all this works but I suspect that what's happening here is that since the chef node is destroyed prior to this being called, the aws_instance provider is unable to derive the instance id from the name of the node and therefore the instance stays running.

**Comment by mwiczynski-cartera** [comment]
I see similar thing happening, not sure if same as this.  If I run the 'converge' recipe twice, the destroy recipe works.  The first time I run converge recipe I get a timeout/exception when the chef client run is waiting to connect to the aws instance.  If I re-run the same recipe it connects and does the rest of the converge(chef installs/runs) on the aws instance.  Then I am able to destroy the aws instance using chef-provisioning.  After the first failed run I see a node created in my chef server org.  But it is missing attributes since chef-client on aws instance never ran.  If I run the destroy recipe at this point it deletes the node from chef server but the aws instances is still running.   It would be nice if the destroy provision recipe was able to destroy the ami instance(if that is possible).  I ended up with 10 aws instances running before I noticed what was happening.  Of course while posting this I tried reproducing the problem and now I can't.

@kreisys, do you see any exceptions during chef-client run?  

This is part of the exception I see:
```
- been waiting 110/120 -- sleeping 10 seconds for frontend_var_fe (i-e3f4043a on aws) to be connectable ...
    - frontend_var_fe is now connectable[2015-10-30T12:15:42-04:00] INFO: Reading key fe-test-key from file /Users/mwiczynski/.ssh/fe-test-key.pem
[2015-10-30T12:15:42-04:00] INFO: Processing chef_node[frontend_var_fe] action create (basic_chef_client::block line 57)
[2015-10-30T12:15:42-04:00] INFO: Executing sudo cp /etc/chef/client.pem /tmp/client.pem.2374401037 on a-user@some.public.ip
[2015-10-30T12:15:52-04:00] ERROR: Unable to download /etc/chef/client.pem to /tmp/client.pem.2374401037 on a-user@some.public.ip -- execution expired
[2015-10-30T12:15:52-04:00] INFO: Executing sudo rm /tmp/client.pem.2374401037 on a-user@some.public.ip
[2015-10-30T12:16:02-04:00] WARN: Unable to clean up /tmp/client.pem.2374401037 on a-user@some.public.ip -- execution expired
[2015-10-30T12:16:02-04:00] INFO: Processing private_key[in_memory] action create (basic_chef_client::block line 88)

    - generate private key (2048 bits)[2015-10-30T12:16:02-04:00] INFO: Executing sudo ls -d /etc/chef/client.pem on a-user@some.public.ip

    ================================================================================
    Error executing action `converge` on resource 'machine[frontend_var_fe]'
    ================================================================================
    
    Chef::Provisioning::Transport::SSH::InitialConnectTimeout
    ---------------------------------------------------------
    execution expired
```

**Comment by kreisys** [comment]
I'm pretty sure this does not happen anymore.
