### ISSUE TITLE
Failure when creating security groups

### ISSUE THREAD

**Issue by tpetchel** [chef/chef-provisioning-aws#57]
I encountered this as well as a few folks in the field. Typically you can just run chef-client again to move past it. Seems related to a similar timing issue where compute instances would fail on creation.

Example output:
https://gist.github.com/tpetchel/e2b808642860913b6eff

Another example (different user)
https://github.com/opscode/learn-chef-beta-content/issues/5

**Comment by lynchc** [comment]
I'm guessing nellshamrell's issue is something completely different, but I also saw an issue very similar to this when writing the eip provider. I would have to converge twice because hydrate wasn't being called correctly on the databag. I manually added a hydrate call for the EIP provider but this error will effect any resource using databags for attribute storage. I have an issue filed for this in chef/chef-provisioning#242
