### ISSUE TITLE
Security Groups 

### ISSUE THREAD

**Issue by lcc2207** [chef/chef-provisioning-aws#67]
Can an option be added to remove any entries in the security ingress/egress that are not in the chef run?  Meaning if someone were to manually add a rule to security group, it appears the current implementation leaves this rule in place.

**Comment by stliang** [comment]
I found that if I manually remove a security group and rerun the recipe that created the security group in the first place, the recipe error out stating that it can not find the security group which I just deleted manually:

Recipe: webserver::provision
  * aws_security_group[sg-ssh] action create
    
    ================================================================================
    Error executing action `create` on resource 'aws_security_group[sg-ssh]'
    ================================================================================
    
    AWS::EC2::Errors::InvalidGroup::NotFound
    ----------------------------------------
    The security group 'sg-b543d2da' does not exist


In principle, chef should restore my desire state if someone change it out of Chef's provisioning process.  I found that Chef keeps the security_group_id such as 'sg-b543d2da' in the  /root/chef-repo/data_bags/aws_security_groups directory.  Since AWS generates a new security_group_id, there is no way Chef is going to be able to restore user's desire state based on security_group_id at least in the case of deletion.  Not sure this is a bug or feature because if Chef is going to based on security group name, AWS does not seem to enforce uniqueness on name.

**Comment by jkeiser** [comment]
Crud, security group names are not unique?  This is a priority then.

**Comment by pburkholder** [comment]
@jkeiser I think you're misreading the comment. The AWS Security group IDs are unique. The issue arises since we have inconsistent sources of truth: the data bags, and the AWS API.

@tyler-ball and I were discussing if using data-bags to back AWS resources is the right thing. It seems that the Chef::Resource::DataBagResource is a good thing when there's no way to determine resource state directly, but when the AWS API can provide that, then the data_bag will be at odds with reality if something changes the AWS resource outside of the Chef context.

In this case, the problem is at https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_security_group.rb#L76, where the call to EC2::AWS::EC2SecurityGroupCollection returns an AWS::EC2::SecurityGroup object, regardless of whether such a group actually exists.  Since that's non-nil, the create action then calls the 'apply_rules' (https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_security_group.rb#L51) method, where `security_group.authorize_ingress` blows up. E.g.:

    $ pry
    [1] pry(main)> require 'aws'
    => true
    [2] pry(main)> ec2 = AWS::EC2.new
    => <AWS::EC2>
    [3] pry(main)> sg = ec2.security_groups['sg-feeddeed']
    => <AWS::EC2::SecurityGroup id:sg-feeddeed>
    [4] pry(main)> # returns truthy even though no such sg exists, then:
    [5] pry(main)> sg.authorize_ingress(nil,nil)
    AWS::EC2::Errors::InvalidGroup::NotFound: The security group 'sg-feeddeed' does not exist

What we need is a consistent way to load_current_resource based on API calls to AWS it seems.

**Comment by jkeiser** [comment]
Oh!  There is good reason to use data bags to back AWS resources if and only if there is no unique "name" field that corresponds to the thing we're trying to modify.  If you can look it up in AWS when the user says aws_security_group 'name', then that's what we should use, never the data bag.  Instances and load balancers, on the other hand, do require data bags, because the only unique identifiers for them is the amazon ID.

Not only that, we store WAY too much information in some of our data bags (like load balancers).  We should not store information we can retrieve from AWS in there (as you point out).  We should store just enough information to look up the thing in AWS, and no more.  There is a bug filed on this for data bags.  I think instances are clear (but not sure right now, and going to bed :).

**Comment by zeroXten** [comment]
I've also noticed that if you change the source IP for a security group rule, then Chef simply adds a new rule and doesn't replace or delete the previous rule. I presume the same would apply to other fields such as port.

**Comment by jkeiser** [comment]
I have code locally that should address this. Still need to test it.

**Comment by tyler-ball** [comment]
This should be fixed in the latest version of chef-provisioning-aws - please re-open if people are finding security groups to be non-convergent.
